language: r

r:
  - release

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

jobs:
  allow_failures:
  - os: osx
  include:
  - os: linux
    dist: bionic
    before_install:
      - sudo apt install mecab
      - sudo apt install libmecab-dev
      - sudo apt install mecab-ipadic-utf8
      - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - os: osx
    before_install:
      - brew cask reinstall java
      - brew cask info java
      - brew install mecab
      - brew install mecab-ipadic
      - export LD_LIBRARY_PATH="/usr/local/Cellar/mecab/0.996/lib:$LD_LIBRARY_PATH"
      - brew install llvm
      - export CC="/usr/local/opt/llvm/bin/clang"
      - export CXX="/usr/local/opt/llvm/bin/clang++"
      - export CXX11="$CXX"
      - export CXX14="$CXX"
      - export CXX17="$CXX"
      - export CXX1X="$CXX"
      - export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
      - export CXXFLAGS="-I/usr/local/opt/llvm/include"

before_script:
  - R CMD javareconf
  - export JFLAGS="-target 1.7 -source 1.7"
  - R -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'

cache:
  packages: true
