language: r

r:
  - release

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

git:
  depth: 3

branches:
  only:
    - master

os: osx

addons:
  homebrew:
    packages:
      - mecab
      - mecab-ipadic

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

before_install:
  - R -e "install.packages('rJava', type = 'source')"

install:
  - R -e "0" --args --bootstrap-packrat
  - R -e "packrat::restore(restart = FALSE)"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
