language: r

os: linux
dist: bionic
r:
  - release

warnings_are_errors: false

git:
  depth: 1

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

r_github_packages:
  - jimhester/lintr

before_install:
  - sudo add-apt-repository -y ppa:cran/poppler
  - sudo apt-get install -y libpoppler-cpp-dev
  - sudo apt install mecab
  - sudo apt install libmecab-dev
  - sudo apt install mecab-ipadic-utf8
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"

before_script:
  - R CMD javareconf
  - Rscript -e 'install.packages("RMeCab", repos = "https://rmecab.jp/R", type = "source")'

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

cache:
  packages: true
