---
title: "Benchmark"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
header-includes:
  - \usepackage[utf8]{inputenc}
vignette: >
  %\VignetteIndexEntry{Benchmark}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)

if(!require(microbenchmark)) stop()
if(!require(ggplot2)) stop()
if(!require(stringi)) stop()
if(!require(RMeCab)) stop()
if(!require(RcppMeCab)) stop()
if(!require(rjavacmecab)){
  devtools::load_all()
}
```

## ベンチマーク

### 比較対象

- RMeCab::RMeCabC() (ver 1.00)
- RcppMeCab::pos() (ver 0.0.1.3)
- rjavacmecab::cmecab() (ver 0.1.4-1)

RcppMeCabは本家の[junhewk/RcppMeCab](https://github.com/junhewk/RcppMeCab)からビルドできないため、[ltl-manabi/RcppMeCab](https://github.com/ltl-manabi/RcppMeCab)を利用しています。

### 結果

```{r}
str <- "キャピキャピ音が高くなってきたら、ほんとに出してくれの合図です！　しっかりここではコミュニケーションとってください"
str_utf8 <- stringi::stri_enc_toutf8(str)

tm <- microbenchmark::microbenchmark(
  RMeCab::RMeCabC(str),
  RcppMeCab::pos(str_utf8), ## MeCabの辞書はUTF-8でコンパイルしています
  rjavacmecab::cmecab(str),
  times = 500L
)
summary(tm)
```

```{r}
ggplot2::autoplot(tm)
```

### セッション情報

```{r}
sessioninfo::session_info()
```

