---
title: "Explore datasets"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
header-includes:
  - \usepackage[utf8]{inputenc}
vignette: >
  %\VignetteIndexEntry{Explore datasets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)

library(dplyr)
library(DT)
if(!require(rjavacmecab)){
  devtools::load_all()
}
```

## AozoraBunkoSnapshot

```{r}
data("AozoraBunkoSnapshot")
snapshot <- dplyr::sample_n(AozoraBunkoSnapshot, 10) # Because it is too large to show whole entries, sampling 10 rows.
knitr::kable(snapshot, "html")
```

## MiyazawaKenji

```{r}
data("MiyazawaKenji")
DT::datatable(MiyazawaKenji, style = "bootstrap")
```

## ExtendedLettersJp

```{r}
data("ExtendedLettersJp")
DT::datatable(ExtendedLettersJp, style = "bootstrap")
```

## OneLettersJp

```{r}
data("OneLettersJp")
DT::datatable(OneLettersJp, style = "bootstrap")
```

## StopWordsJp

```{r}
data("StopWordsJp")
DT::datatable(StopWordsJp, style = "bootstrap")
```

