name: R-CMD-check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        java: [11]
        r-version: ['4.0.0']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install libraries
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt install mecab
          sudo apt install libmecab-dev
          sudo apt install mecab-ipadic-utf8
          sudo ldconfig
      - name: R CMD javareconf
        run: sudo R CMD javareconf
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "rJava"))
          remotes::install_github("r-lib/covr")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-multiarch", "--no-vignettes", "--no-manual"), build_args = c("--no-build-vignettes", "--no-manual"), error_on = "error")
        shell: Rscript {0}
      - name: Codecov
        run: covr::codecov()
        shell: Rscript {0}